# Generated by Django 4.2.17 on 2025-01-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('love', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='products/')),
                ('unit', models.PositiveSmallIntegerField()),
                ('rate', models.DecimalField(decimal_places=1, max_digits=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
