# Generated by Django 4.2.17 on 2025-01-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, max_length=100),
        ),
    ]
