# Generated by Django 4.2.17 on 2025-01-29 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_market_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='selling',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='market',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
