# Generated by Django 4.2.17 on 2025-01-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_market_selling_alter_market_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
