# Generated by Django 4.2.17 on 2025-01-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_market_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='kind',
            field=models.CharField(choices=[('FRUIT & VEGAS', 'FRUIT & VEGAS'), ('JUICES', 'JUICES')], default='JUICES', max_length=25),
            preserve_default=False,
        ),
    ]
