# Generated by Django 4.2.17 on 2025-01-29 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_market_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
