# Generated by Django 4.2.17 on 2025-01-29 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_customers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='purchase',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='home.market'),
        ),
    ]
