# Generated by Django 4.2.17 on 2025-01-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_customers_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='purchase',
        ),
        migrations.AddField(
            model_name='customers',
            name='purchase',
            field=models.ManyToManyField(to='home.market'),
        ),
    ]
