# Generated by Django 4.2.17 on 2025-01-29 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_customers_purchase_customers_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='purchase',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('product', models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.market')),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='cart',
            field=models.ManyToManyField(to='home.cart'),
        ),
    ]
