# Generated by Django 4.2.17 on 2025-01-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_cart_number_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
