# Generated by Django 4.2.17 on 2025-01-31 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_market_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='order',
        ),
    ]
