# Generated by Django 4.2.17 on 2025-02-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_cart_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='cash',
        ),
    ]
